package com.sound.healing.cards;

import java.util.HashMap;
import java.util.StringTokenizer;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.math.MathUtils;
import com.badlogic.gdx.utils.Array;
import com.sound.healing.actors.SceneHandler;
import com.sound.healing.custom.Spread;

public class AllCards {
	
	private Card[] cards = new Card[52];
	private Card currentCard;
	private int individual = 0;
	private Array<Card> revealCards, loadCards, inCards;
	
	private static final AllCards INSTANCE = new AllCards();
	
	public AllCards() {
		createCards();
		currentCard = cards[0];
	}
	
	private void createCards() {
	CardSpec[] c = new CardSpec[52];
	c[0] = new CardSpec("Tribal Chant", CardType.ROOT, "1.png", "Indigenous peoples are still aware of the power of the voice, and use it in their daily practices to heal, to calm and to energise. Although modern technology may increasingly rule our lives, the vibrational sound of the earth is ancient, as is the song of our ancestors held in the cellular memory of our bodies.  When we really connect to our roots - to our passion, our fire, our earthiness, we can literally move mountains.  So it's time now to reconnect to our indigenous soul, to chant, to dance, to unite in song with the One Tribe of all humanity. Ignite your inner flame by finding a deep, red sound to vibrate your base chakra, and get passionate about the amazing gift of being alive on this earth, with all its challenges and rewards. Just open your mouth, breathe in deeply to the root - and become a human didgeridoo!", "071.mp3", "072.mp3", 1);
	c[1] = new CardSpec("Sound Ground", CardType.ROOT, "2.png", "What does it mean, to be 'in the body?' To be grounded?  It means to feel and experience everything that is going on inside you, without closing off; to listen to the body's messages and act on them; and at the same time, to connect to and be in harmony with the power of the earth's vibration. The simple beauty of the voice is that when we sound tones, it immediately brings us right into our inner body, 'grounding' us to be more practical in our lives.  Standing on 'sound ground' helps us to have a good, solid foundation: unshakeable and rooted, regardless of life's storms which rage around us personally and professionally.  Find a rich, deep red sound, send it down to the earth through your feet, and BE here and now in this moment. Discover the joy of being pure, life force energy, grounded on this planet.", "074.mp3", "075.mp3", 2);
	c[2] = new CardSpec("Highland Air", CardType.ROOT, "3.png", "We all get stuck in the head at some point, dizzy, unrelated, floating away, disconnected, with problems and ideas whirling round on endless tape loops in our minds. We're in the body, then we're in the head, and sometimes we retreat there because we simply can't deal with the emotions taking place inside us. If we 'live' in the head, we believe we can control or simply avoid our pain. But we are actually here on the earth to be in the body, to learn and experience from it, and when we are ungrounded, we can't function properly on a practical level.  It's time to come down to earth.  Take off your shoes, walk barefoot on the grass, find a deep red sound and direct all those heady thoughts down through your body and into the soil. Stop being an airhead and become an active member of the ground force!", "076.mp3", "077.mp3", 3);
	c[3] = new CardSpec("Big Bang", CardType.ROOT, "4.png", "Have you ever felt as though you were sitting on a volcano?  All those angry thoughts and feelings, resentments and frustrations bubbling away underneath?  It takes more energy to hold anger down, to suppress it at the base of the spine, than to let it out.  We are taught that anger is wrong, but a powerful flash of good, clean, honest, straight-speaking can clear the air both with ourselves and with others and help keep our boundaries intact. The problem with anger is that if it isn't expressed, it slowly and silently grows, until it explodes in a huge and damaging eruption. Find a sound now.  Deep, fiery, as strong as you want. Connect in your memory with everything that is causing you pain, anger and frustration, and release all the feelings down into the earth with sound. Detonate your emotional time bomb, and create a new universe of peace within.", "078.mp3", "079.mp3", 4);
	c[4] = new CardSpec("Touch Bass", CardType.ROOT, "5.png", "Most of us live in such a left-brained, logical electronic society, in concrete blocks and buildings, with central heating and air conditioning, that we cannot help vibrating more and more out of harmony with the rhythm of the earth.  Yet we belong to Mother Earth, and we really need to take time to touch base with her.  When did you last stand out on the earth barefoot, lie on the grass and connect with her nurturing energy?  When did you last breathe in unity with Mother Earth, express your gratitude for everything she offers so freely to you?  Close your eyes, connect to the earth through the soles of your feet and visualise sending down strong red roots as you sound deep tones.  Become a Tree of Life and ground yourself by rooting into the planet.", "080.mp3", "081.mp3", 5);
	c[5] = new CardSpec("Plainsong", CardType.ROOT, "6.png", "'Plainsong' is a medieval mode of music, sung in unison with free rhythm. There is also an additional meaning here of 'song of the earth plains', as the 'unison' created by sounding tones is between heaven and earth.  The root chakra represents our fire, passion, power and life force, all of which become depleted with daily life. There is an endless supply of energy always available to us from The Source and we can connect to it through the crown centre on top of the head.  Close your eyes, focus on the in and out breath to centre yourself, visualise the crown gently opening, and find a high red sound to unify you with The Source. Visualise the energy moving down your spine to the root chakra, letting the sound slide from high to low at the same time. Allow the heavenly energies to nourish, revitalise and vibrate your life force.", "082.mp3", "083.mp3", 6);
	c[6] = new CardSpec("Resonance", CardType.SACRAL, "7.png", "Resonance (from the Latin 'resono', to sound again, or re-echo) is the continuous vibration of sound, literally 're-sounding' itself, and deriving from this is the concept that we can also 'resonate' with a person, place or idea: that is, we 'continue' their original reverberation by 'echoing' our agreement, in unity with it.  So a 'resonant' sound is also harmonious and pleasant.  When we are truly in harmony with the creative source within us, our whole being literally resonates with joy.  The sacred law is that like attracts like: therefore what we send out we will most certainly magnetize back to ourselves.  Breathe in a sense of expectation. Inhale a joyful vivid, orange colour into the second chakra and open wide the petals of your own creativity. Find a sound which resonates exactly with what you want to create fresh and new in your life, and send it out into the world now!", "084.mp3", "085.mp3", 7);
	c[7] = new CardSpec("Vibration Creation", CardType.SACRAL, "8.png", "Every new breath is a new beginning, a new chance to start again, to understand and to know that we always have a choice: that we can be co-creators of our lives with The Source.  Life is so amazing, because the truth is, we do have everything we need within us.  Our creativity, our fecundity, is immense. What we focus on, we will become.  Using sound to vibrate our creative centre can effortlessly help us to raise our vibration and give birth to new joys, new projects, new relationships in our lives. Focus on your sacral area. Deeply breathe the vibrant orange joy of life into your second chakra until you are bubbling over with energy, and into this fertile bed of harmony, 'plant' new seeds of sound, one for everything new you would like. Continue to nurture the seeds with positive tones, and see them bursting into life. You are your own creation!", "087.mp3", "088.mp3", 8);
	c[8] = new CardSpec("Over Strung", CardType.SACRAL, "9.png", "Technology was supposed to be the means to help us create more free time, but paradoxically, because we can now do everything so quickly, we simply cram more into our daily routine. As life spins faster, we push ourselves to keep up with the pace, regardless of personal cost, and the resulting stress and tension can tighten the strings of our nervous system to breaking point. Being overtired, stressed and blocked means our creative energy doesn't flow freely.  Solutions evade us and problems intensify. An overstrung piano, however, is where the strings are strung diagonally across each other to give additional length, creating a better tone.  It's time for you to stretch out inside and release your inner tensions. Focus deep calming in-breaths down into the second chakra, breathe out your worries, and find soft, orange sounds to soothe yourself as new solutions effortlessly float into your mind.", "089.mp3", "090.mp3", 9);
	c[9] = new CardSpec("Lost Chord", CardType.SACRAL, "10.png", "What is more scary than the blank page?  As soon as you come up with an idea and commit it to the spoken or written word, sing it or play it, draw it or build it, you can be criticised, belittled, told you are not good enough. Why do we sabotage our own creations? What is it that stops us from completing our projects, or leaves us stuck half way, desperately searching for that lost chord, that perfect idea that is dancing just out of reach?  The answer lies within us: we are our own worst critics with our self-talk. Using sound can help to quieten the continuous chattering of the brain, increase our alpha waves and open our intuition.  Bring into your mind any current blocks in your projects.  Focus the feeling down into the second chakra, release with a strong, orange sound and allow the petals of your creativity to unfold.", "091.mp3", "092.mp3", 10);
	c[10] = new CardSpec("Perfect Pitch", CardType.SACRAL, "11.png", "Why do some people succeed with their ideas, while others fail to materialise them? The inspiration is there, but inspiration is not enough.  We must be able to ground our ideas to manifest them.  To 'pitch' an idea is to present it professionally. 'Pitch' is also the place where the game, the action takes place - on the ground. 'Perfect pitch' has the additional musical meaning of someone's ability to instantly recognise the tonic sol-fa of a note and whether or not it is in tune.  So we need to be in perfect harmony with our ideas, but to give them the best chance of being born, we have to ground them.  Breathe in now, connect down to the second chakra and feel the energy of your creativity vibrating inside. Find a strong orange sound that resonates with this feeling and send the sound down to deeply connect with the earth.", "093.mp3", "094.mp3", 11);
	c[11] = new CardSpec("Unison", CardType.SACRAL, "12.png", "Have you noticed how some of your most amazing ideas come when you're not even thinking about it?  That 'Aha!' moment, when you're walking along the edge of the ocean, gazing at a sunset, breathing in a mountain range, or sitting under an ancient tree? In those moments, we feel our One-ness, our connection to the Divine, when all of life seems to flow through us.  In those moments, you don't need to try: life writes itself through you in the gift of a song or a poem, a mathematical solution, a swirl of colour. If you can, find a peaceful place in nature. Sit with your eyes closed and focus on the breath. Sound a high orange tone to gently open the crown and connect you to Divine Wisdom until you feel in unison. Then gently slide the tone from high to low, moving energy down the spine to nourish the sacral as you do so.", "095.mp3", "096.mp3", 12);
	c[12] = new CardSpec("Warrior Song", CardType.SOLARPLEXUS, "13.png", "There's a warrior inside every one of us.  We may no longer daub ourselves in war paint or 	brandish spears and shields, but at some point in every person's life, there is that moment of 	knowing:  this is it!  Grit your teeth, find your courage and stand to face the antagonist.  More 	often than not, it is the enemy within us that causes those doubts and fears to gnaw away in our 	solar plexus, making us feel 'lily-livered' and inadequate.  But whatever your current 	challenges may be, it's time for you to find your own personal battle cry. Stand with your feet 	firmly placed on the ground.  Breathe a strong, warm golden yellow glow into your solar 	plexus. Feel the energy expanding as you breathe into your centre, focusing on all your positive 	qualities. Then find a bright yellow sound for your inner strength and pulse it out to the world!", "097.mp3", "098.mp3", 13);
	c[13] = new CardSpec("Rising Star", CardType.SOLARPLEXUS, "14.png", "How many of us are brought up to believe we are in the right place, at the right time, doing the right thing in the right way?  That it is enough, just to simply be ourselves, that we are perfect, exactly the way we look?  Very often we are taught it is selfish and egotistical to appreciate our own qualities: yet if we don't value ourselves, if we don't have a sense of our own worth, how can we expect others to value us?  Everyone is unique.  Everyone has their own special brand of star quality, their own individual gift they brought into this life with them.  It's time to honour yourself.  Breathe a strong golden colour into the solar plexus. Feel the petals of your self-worth opening.  Connect to this feeling with vibrant yellow sound, focus it like a laser beam and beam the sound and colour out to your friends, families, colleagues, the world!", "100.mp3", "101.mp3", 14);
	c[14] = new CardSpec("Distant Drums", CardType.SOLARPLEXUS, "15.png", "Have you noticed fear is always in the future?  Our mind is brilliantly expert at making up ingenious stories about things which haven't happened yet and possibly never will: our projected anxieties. Every time we focus on fear, our body releases a whole chemist's shop of adrenalin-type 'drugs' into our bloodstream, and if we're in a constant state of agitation, these chemicals can affect the immune system and our health. We can't control a future that has not yet happened, but we can make sound now to ground us strongly in the present tense, where we can deal with our problems. Bring your greatest current fears into your mind and feel them in the solar plexus.  Connect to this feeling as you breathe in clear golden energy, and release the emotion over and over with strong yellow sound. Then sit quietly, and visualise breathing fresh gold courage into the open centre.", "102.mp3", "103.mp3", 15);
	c[15] = new CardSpec("Unsound", CardType.SOLARPLEXUS, "16.png", "There is a wonderful phrase, 'to sound the depths' of the ocean, and 'unsounded' or 'unfathomed' seas are those whose depth is still unknown.  There are parts of us that are buried deep, hidden in the uncharted waters of ourselves.  Sometimes we deny our true selves because we simply feel we don't deserve to be acknowledged, or we are afraid that if we show who we really are, it will upset or alienate people. So we become 'unsound', in the sense of feeling we are imperfect, erroneous, unstable, and we hold these old beliefs deep in the body's cellular structure.  It's time to let go.  Breathe in strong yellow, connect to the solar plexus, feel all those feelings of not being good enough and find one almighty sound to release the past. Finish by affirming 'I am an Amazing Being!'", "104.mp3", "105.mp3", 16);
	c[16] = new CardSpec("Chorale", CardType.SOLARPLEXUS, "17.png", "The earth, so the Native American Indians say, is our true mother.  We receive everything we need from her boundless, never-ending abundance as she reflects back to us the cycles of birth, fertility and death. When we feel unsure, insecure or afraid, simply being in nature and connecting with that strong Earth Mother energy can calm, reassure and ground us; and when we are really connected to the earth, we experience both our own uniqueness and the inner peace of being at one with all creation.  A Chorale was originally a simple hymn sung in unison, and you can join with the song of the earth's vibration.  Breathe your own uniqueness into the solar plexus, find a deep yellow sound of unity with all that is, and send it down through your feet to the earth.  Become a pure note in the chorale of life.", "106.mp3", "107.mp3", 17);
	c[17] = new CardSpec("Super Troopers", CardType.SOLARPLEXUS, "18.png", "'Super troopers' are huge, brilliant spotlights, beamed down onto rock performers on stage, and sometimes we need to summon the light, call in the spiritual troops to guide us with our current challenges. There is always help waiting in the angelic wings, but how can life deliver what we honestly need if we don't give clear signals by asking?  At this precise moment in time, you alone know what you require to give you courage to face your fears and move forward. Sit quietly. Focus on the breath and visualise the crown gently opening.  Find a high, clear yellow sound to connect with the angelic realms.  Keep sounding until you fuse to the golden light of your Super Trooper helpers, then slide the tone and the light down your backbone into the solar plexus. Focus on the quality you need right now, and sound it into the centre of your Sun. Go for gold!", "108.mp3", "109.mp3", 18);
	c[18] = new CardSpec("Heartsong", CardType.HEART, "19.png", "How does it feel when your heart sings? When that sudden rush of joy pours through you, and in that instant, you are filled with compassion, with understanding, with love for everything and everyone?  It is as though a beam shines out of your heart, linking you to all creation, and this is as it should be.  Our heartsong is the melody of our soul expressing itself in perfect harmony.  What stands in our way is the cleverness of the mind, distracting us from who we truly are. But we can let go of the mind. Surrender now.  Focus on the heart and visualise breathing in and out through the centre. Find a soft, green healing tone of Unconditional Love towards yourself and others and as you sound it, let the feeling expand into perfect trust, until you melt into the joy with emerald sound. This is your heartsong.", "110.mp3", "111.mp3", 19);
	c[19] = new CardSpec("Ovation", CardType.HEART, "20.png", "When we think of ovations, we think of praise, of applause, the laurels of success, but the original meaning of the Latin ovare is to exult and rejoice. Gratitude is a simple quality, but one which we express too rarely. How often do we take even our ability to breathe for granted?  We walk round with eyes closed, complaining at the familiarity of everything. Only when we are truly in the heart can we experience the Oneness of life, and sound centres us in the heart. There is a standing ovation due now: an ovation to Life and to yourself for all you have been, all you are, and all you will become. Focus on the heart.  Visualise breathing in clear life force energy, and find a warm green tone of gratitude for everything you have experienced in your life.  Let the tone become your heartfelt exultation and thanksgiving at being alive.", "113.mp3", "114.mp3", 20);
	c[20] = new CardSpec("Heavy Metal", CardType.HEART, "21.png", "It takes great strength to be vulnerable, to continually hold the heart open and receptive. From small children, we learn to hide or disguise our pain to survive.  Sometimes we retreat from intimacy temporarily to heal our wounds, or decide we will no longer allow ourselves to feel.  So we construct armour around the heart, a protective shield to keep the enemy at bay. Closing the heart and building defences may prevent more hurt, but it also excludes the very thing we need: love.  We also need forgiveness for ourselves and others. Visualise breathing in and out through the heart centre. Find a soft, green healing tone of Unconditional Love and release any painful feelings and memories with sound. Let the tone become stronger and stronger.  Feel the armour melting away, until there is just your open heart and the sound of freedom.", "115.mp3", "116.mp3", 21);
	c[21] = new CardSpec("Cacophony", CardType.HEART, "22.png", "Sometimes we need to make our boundaries clear to others.  When we don't define what is acceptable behaviour towards ourselves, people can take advantage, invading our space with demands that we feel we can't say 'no' to.   Cacophony (from the Greek 'phone' meaning sound) is inharmonious noise, creating discord. When people make demands which are not in tune with your real needs, when you don't express your truth, inner discord is exactly what you will experience. How you allow people to treat you is ultimately your choice. It's time to redefine your boundaries.  Focus on the heart with a strong, warm, green sound to expel everybody else's expectations, needs, feelings and problems, until your heart feels clear.  Bring into your mind how you really want to be treated. Put that feeling into a sound and send it out into the world with clarity, strength and love.", "117.mp3", "118.mp3", 22);
	c[22] = new CardSpec("Harmonics", CardType.HEART, "23.png", "Although every living creature has as much right to be on this planet as we do, humankind appears to have claimed sole ownership of the earth.  Rainforests shrink, oceans rise, animal and plant species diminish along with their natural habitats, but we continue the path of devastation, scarcely pausing to appreciate before we destroy. The Native Americans Indians offer gifts to Mother Earth before they take, and if we don't have the time or inclination to do this, we can at least create harmonic resonance with our voices, adding overtones to the basic earth note.  Sacred sound has been used for centuries to heal the earth.  So focus on your heart centre, breathe in the soft green hues of nature until your heart brims with abundance, gratitude and love, and send healing, harmonious green tones from your heart through your feet to the earth.", "119.mp3", "120.mp3", 23);
	c[23] = new CardSpec("Benediction", CardType.HEART, "24.png", "We are never alone, and we are never without love. We simply forget we are always connected to the Source. There is an unfailing, endless supply of love and energy, and all we need do is relax, open and allow it to fill us.  'Benediction' (from the Latin bene dicere, to praise) is a sung or spoken blessing, and we can literally 'sound down' the blessing that is always available to us.  Sit quietly, focus on the in and out breath, and visualise the crown gently opening.  Find a high, pure, green sound to connect to the source of Endless Love.  Keep sounding the tone, then visualise the energy moving easily and effortlessly down in a spiral of light, through your crown into the heart centre. Continue until your heart is filled with this perfectly attuned vibration. You are safe. You are connected.  You are In Love.", "121.mp3", "122.mp3", 24);
	c[24] = new CardSpec("Fanfare", CardType.THROAT, "25.png", "There are many ways to express our truth.  Sometimes we can only do it with forcefulness and anger; sometimes by playing ourselves down or even making a joke around it, sometimes only with tears.  But if you really want your truth to be heard, then try to express it with the vibration of love in your voice.  Clear, honest communication rooted in the heart creates the vibrant sound of your own authenticity, which people will subconsciously respond to.  A 'fanfare' is a flourish of trumpets.  Breathe into the throat centre and find a bright blue sound to encapsulate everything you want to express in this moment.  As you release the sound, visualise waves of blue pulsing out to whoever or whatever you want to communicate with.  Joyfully trumpet forth your truth and lovingly announce who you are to the world.", "123.mp3", "124.mp3", 25);
	c[25] = new CardSpec("Anthem", CardType.THROAT, "26.png", "An anthem was originally a song of praise or gladness set to sacred music, although nowadays we tend to think of anthems in terms of national identity. There are many different levels to finding your own identity and being your authentic self, but eminently important are the acts of living, speaking and thinking the truth. It takes courage to find your own voice, speak your own words and create your own individual life path. When we do find the inner strength to be ourselves, old patterns and old friends may drop away, but Life always finds the magic to create anew and support our initiative. This Anthem is for you. Visualise breathing vivid blue into the throat centre. Bring into your mind all the changes you are making in your life to be more authentic.  Find a strong, blue sound, fill it with that feeling, and let rip!", "126.mp3", "127.mp3", 26);
	c[26] = new CardSpec("Speechless", CardType.THROAT, "27.png", "What is it that stops us from expressing our real honest-to-goodness truth? Sometimes we are afraid of hurting people's feelings, yet what we want to say is often what they most need to hear.  Sometimes we simply don't feel confident about ourselves and our ideas.  Maybe we were belittled or unsupported in our tender years, at school, at home, and maybe that still continues today. Whatever the reason, if you feel strangled, tongue-tied, unworthily shy or inadequate or if you are simply afraid of a hostile reaction when you say what you're really thinking, now is the time to find your voice.  Focus on the blocked feeling in your throat and breathe in strong blue.  Find a vibrant blue sound and as you tone, visualise the throat opening, releasing all that stuck energy and pulsing with your truth. Your voice is a muscle and will strengthen with each gentle workout.", "128.mp3", "129.mp3", 27);
	c[27] = new CardSpec("Cracked Bells", CardType.THROAT, "28.png", "Coins were once tested by throwing them on a counter to see if they would 'ring true' (the clear resonance of vibrating metal) or 'ring false' if counterfeit.  We say 'sound as a bell', because flawless bells 'ring true', whereas cracked bells have a dull, powerless tone. Our words also vibrate with subliminal messages -  the 'ring of truth' or the opposite.  So are you pretending everything is fine, when you're dying inside, or seething with anger?  Have you replaced your own integrity with others' words?  Are you telling those white lies to protect someone from a truth they really need to face? Whatever your reasons, it's time to let go.  Focus on the throat, breathe in strong blue and summon those unexpressed secrets vividly to mind.  Connect with the emotion and sound a powerful blue tone to release, until the throat feels clear.  Now sound the vibration of your truth.", "130.mp3", "131.mp3", 28);
	c[28] = new CardSpec("Dawn Chorus", CardType.THROAT, "29.png", "It is very often only our consciousness that prevents us from expressing. Were you ever aware of a blackbird comparing itself to another, of a thrush feeling less worthy because its partner was warbling the joys of life in such beautiful song? We get so caught up in the comparison of the mind, in having to be perfect, successful and excellent, that we literally freeze up inside, causing the throat muscles to tense and tighten. There are no weakest links in the orchestra of nature. All you need to do is get up early and listen to the dawn chorus to hear creation tuning up into one magnificent symphony together. Find a quiet place out on the earth now, listen to the sounds of nature, and bring a harmonious blue tone into your throat to connect.  Send the sounds down your backbone to the earth in oneness.", "132.mp3", "133.mp3", 29);
	c[29] = new CardSpec("Sacred Sound", CardType.THROAT, "30.png", "When you are really working in service with sacred sound, it can feel as though the angels are singing through you.  The energy pours in through the crown and issues from the mouth in streams of sound and colour.  It becomes effortless and simultaneously relaxing and energising.  So it is with our words: we need to connect to the higher energies and use those sounds to raise our consciousness and vibration with every word we speak: peace in our thoughts, peace in our deeds, peace in our words.  Focus on the breath, visualise your crown chakra gently opening,  find a high, vibrant blue tone and connect to the angelic realms with the sound.  Keep sounding the tone until you really feel one with divine wisdom.  Then slide the sound and colour down from your crown into the throat centre.  Allow the tone to vibrate the throat and visualise every word you speak filled with this sacred sound.", "134.mp3", "135.mp3", 30);
	c[30] = new CardSpec("Silent Music", CardType.THIRDEYE, "31.png", "The answers to everything we need to know lie within us, if we will only take the time to 'tune in' and listen to our inner voice. There is a constant 'chatter' going on inside our heads between the left and right sides of the brain, and using sacred sound is a wonderfully simple method of stilling this. 'Tuning in' actually means adjusting our frequency so that it vibrates in harmony with a sound wave - the song of our inner voice, our intuition.  Silence and stillness helps us to hear this beautiful music. Close your eyes and connect to your third eye.  Breathe in a wonderful, deep, dark indigo colour and visualise the lotus petals opening wide. Find a calm indigo sound to connect to your inner stillness.  Alternate with the sound, followed by silence.  Continue until you feel completely calm.  Then sit in silence and let your inner wisdom speak.", "136.mp3", "137.mp3", 31);
	c[31] = new CardSpec("Mantra", CardType.THIRDEYE, "32.png", "Mantra ('divine speech', or 'tool of the mind') is a Sanskrit word, and the fifty letters of the basic Sanskrit alphabet correspond to the fifty petals on the chakras from base to brow. 'Ohm' is the seed sound for the third eye, where the masculine and feminine energies meet, and contains the principle of Unity. Mantras are positive sounds repeated with the clear intention to change our consciousness and raise our vibration. Close your eyes, breathe indigo into the centre of your third eye and feel it gently opening. Sound a calming indigo ohm and keep repeating the sound, over and over, allowing yourself to relax and become one with it. Sink into a state of bliss and from this place, ask to see the truth. Beam the sound out from your third eye to 'illuminate' all current life situations.", "139.mp3", "140.mp3", 32);
	c[32] = new CardSpec("Rigid Tempo", CardType.THIRDEYE, "33.png", "We are born not only with our crown wide open, but also our intuition.  As we grow in this increasingly left-brained, logical computerised society, we are gradually persuaded by family, peers and the education system, to ignore it: we can only trust what is proven and visible.  There is a natural rhythm and flow to life, but when we rely too much on the left brain, we often try to control everything, particularly our emotions.  We orchestrate and conduct all aspects of our life into an unnatural, rigid tempo, forcing ourselves to march in time with it.  You need to be in balance.  Breathe indigo into your third eye, place your right hand palm downwards on the left frontal temple, and send calming indigo ohm sounds into the left brain.  Visualise the soothing colour and tones pulsing through your hand to relax and release your thoughts.", "141.mp3", "142.mp3", 33);
	c[33] = new CardSpec("Off Key", CardType.THIRDEYE, "34.png", "We think of clairvoyants and mediums as specially gifted people who can 'see' in a way that is simply not possible for others; but the truth is, when we relax into a deep alpha wave state, we can also have incredible flashes of intuition and insight. Sacred sound vibrates the corpus callosum, a bundle of nervous fibres which facilitate communication between the two brain hemispheres, and this simultaneous relaxing and stimulating effect helps create alpha waves, bringing the right and left brain into balance and opening our intuition. Breathe indigo into the centre of your third eye. Place your left hand, palm downwards, on the right frontal temple.   Find a warm, indigo ohm sound for your personal intuition and visualise the colour and tones pulsing through your hand into the right brain to clear out old blocks. Continue to tone, allowing the third eye to open even wider, then sit in the silence and allow yourself to see.", "143.mp3", "144.mp3", 34);
	c[34] = new CardSpec("Tuning Fork", CardType.THIRDEYE, "35.png", "Using sound to open to our intuition is simple and effective, but if we don't firmly ground ourselves, we can be in a state of continuous floating, carried away by the messages we receive. We are spirit incarnated into this body to experience being on the earth, and our intuition will be of little help if we don't use it in a practical way.  When a tuning fork is struck against a solid object, it emanates a perfect pitch for us to tune to.  So we need to 'hit' the earth with the sound of our intuition, to connect intuition to the ordinary, everyday rhythms and sounds of nature as a perfectly natural gift. So breathe indigo into the third eye, find a strong indigo sound to connect to your intuition and send that sound and energy down the backbone through your feet into the earth.  Become a human tuning fork and 'dig' your intuition into solid ground.", "145.mp3", "146.mp3", 35);
	c[35] = new CardSpec("Incantation", CardType.THIRDEYE, "36.png", "Working with our intuition can give us a real sense of our own power, so we need to constantly 	observe ourselves objectively to check that we are focused on and guided by integrity.  	'Incantation', from the Latin 'cantare', to sing, has the additional meaning of 'to use enchantments' in a magical sense.  We can become enchanted by our own ego, or spellbound by the higher vibration of the angelic realms: the choice is ours. Use sound now to clarify your sense of purpose in thought, word, deed and intuition. Focus on the crown chakra and visualise it gently opening. Find a high, clear indigo ohm sound and connect to the Source through the crown. When you feel your oneness with this pure energy, swoop the sound, colour	and vibration down into the third eye. Keep sounding the ohm and allow clarity and integrity to flood into your third eye from above.", "147.mp3", "148.mp3", 36);
	c[36] = new CardSpec("Crystal Grail", CardType.CROWN, "37.png", "Clear quartz crystals can be 'tuned' with sound to be used as powerful healing and transformational tools. The bones of our skull can also be resonated and even help us produce 'overtones' (harmonic tones created by the original fundamental note) when we change the shape of the mouth and literally send sound through passages and into cavities. When we really allow the crown to open, we can joyfully experience ourselves as the Holy Grail: an empty sacred cup, waiting to be filled with pure spirit and unconditional love.  Breathe a clear violet colour into your crown.  Visualise the top of your head gently opening as you tone a high violet sound.  Make the sound as pure, clear and resonant as possible and allow it vibrate through your nasal passages and up into your head.  Be aware of your skull like a large crystal cup, and as you tone, see the empty vessel filling with pure sound, colour and light.", "149.mp3", "150.mp3", 37);
	c[37] = new CardSpec("Attunement", CardType.CROWN, "38.png", "Have you ever noticed how a number of people appear to be randomly working on the same original idea at the same time, unbeknowns to each other?  Or heard top songwriters say the song 'wrote' them, or simply dropped into their mind like a gift?  The Platonic theory of the universe states that everything exists first in idea form, and it does seem that when an idea wants to be born, it's unstoppable. 'Attunement' means 'to bring into musical accord', and if we relax into alpha, we can more easily 'tune into' the Akasha: a record of all that has been and will be. Sit quietly, focus on the breath and sound a pure, high violet tone to open the crown. Stay in the body, but visualise the sound waves connecting out to the source of all wisdom. Keep toning strongly.  Then sit in silence and observe new thoughts flowing into your consciousness.", "152.mp3", "153.mp3", 38);
	c[38] = new CardSpec("Dissonance", CardType.CROWN, "39.png", "We enter this incarnation connected to the source that created us, but at some point during our lives, we may suffer a sense of disconnection, separation or isolation. It is illusion, for we are eternally connected to an unfailing supply of prana and love.  But this feeling of separation only serves to prove our greatest fear: that we are unworthy and therefore unloved. Dissonant sounds are harsh, conflicting, out of harmony, and this is how our inner turmoil can feel as we yearn for love, but affirm such love does not exist.  It does: and you can experience it right now.  Breathe clear violet into the crown, find a strong high violet tone and release all your feelings of separation.  Continue to tone, visualising pure violet light pouring into your crown from The Source, flowing from cell to cell throughout your whole body.", "154.mp3", "155.mp3", 39);
	c[39] = new CardSpec("Lament", CardType.CROWN, "40.png", "There are many different reasons why we cut off from source.  It can happen when we are in the womb, in early childhood, our teenage years, or later life. Shock, trauma, rejection, emotional or physical abuse, world events or simply the challenges of life can cause us to disconnect from any sense of higher purpose or guidance so that we forget our essential self.  To lament is to express grief, often for the dead, and when we disconnect, it can feel as though part of us is dead.  Breathe clear violet light into your crown. Sound a high violet tone to express your own personal Lament of Life, until you feel all emotion is released.  Then find a sound to connect out to higher wisdom, and vibrate your crown with the truth of who you really are:  a beautiful being of light.", "156.mp3", "157.mp3", 40);
	c[40] = new CardSpec("Grace Note", CardType.CROWN, "41.png", "Knowledge is a wonderful thing but there is a saying: to know, and not to do, is not to know.  True wisdom is putting all our miraculous knowledge into practice in our daily lives on earth so that not only do we know the truth, we think it, speak it, honour it and live it. We need to ground our spiritual knowledge, to earth it, so that we can be effective in helping to raise the vibration of consciousness on the planet.  A 'grace note' is a tiny extra note written as an embellishment, and you can use your sound now to be the 'grace note' of divine inspiration Breathe pure violet into your crown chakra, find a high violet sound to connect to universal wisdom, and swoop the sound down from the crown, through the backbone and feet, deep into the earth.  Ground Your Sound.", "158.mp3", "159.mp3", 41);
	c[41] = new CardSpec("Sacred Gong", CardType.CROWN, "42.png", "To experience a gong bath is to feel the whole universe moving through your body with incredible cosmic sound waves, and it is little wonder that there are tuned gongs named after the planets, because you really can hear the sound of creation in the rippling vibrations. The resonance of the bones in the skull also causes vibrations and when we connect with source, we become like an instrument that life beams sound through. Breathe pure violet into the crown and visualise it gently opening.  Stay in the body, but find a high violet sound to connect out to source.  Continue to sound the tone and visualise a violet beam of light spiralling in through the crown and down the spine. When you feel completely in unity with this spiral, connect with the image of a sacred gong. Become the gong, and pulse out the sound.", "160.mp3", "161.mp3", 42);
	c[42] = new CardSpec("Octave Jump", CardType.WHOLEBODY, "43.png", "Have you ever silently experienced and breathed in the energy of a pure white lotus?  There is something inspiring in the tranquillity and vibrancy. We are all Petals of the Divine, and when we step aside and allow Life to express through every single part of us, we can experience our lotus nature: vibrant, beautiful, open, serene. It is this stillness and openness that attracts and manifests each life situation.  The affirmation I AM is immensely powerful and you can use it now to literally chant your vibration to a higher level. Connect with the in and out breath, visualise breathing in pure white sparkling prana, and chant I AM into every chakra and every cell in your body. Sound it into individual chakras or begin at the root and chant up each chakra to the crown.  End by seeing yourself as a pure white lotus and affirm I AM with your whole body.", "162.mp3", "163.mp3", 43);
	c[43] = new CardSpec("Breath of Life", CardType.WHOLEBODY, "44.png", "When we experience ourselves as the serene and beautiful lotus, all barriers disappear and we can breathe with the whole body.  We feel our connection and Oneness with everything that is and know we are simply another expression of universal life force energy manifesting in this body. The power of I AM can really help us to strengthen this connection.  Sit crossed-legged, hands resting on knees, tips of thumbs and index fingers touching. Focus on the in and out breath, and visualise yourself as a pure white lotus, silently affirming I AM as you inhale and exhale. With every inbreath, visualise sparkling white prana pouring in through the pores of your skin. Breathe the prana in with your whole body, and as you exhale, begin to sound I AM.  Continue as long as you wish, then sit in silence and breathe effortlessly with the whole universe.", "165.mp3", "166.mp3", 44);
	c[44] = new CardSpec("Discord", CardType.WHOLEBODY, "45.png", "Sometimes we can't open at all, closing our petals tight to protect us because of past wounds. Sometimes we are too 'open', taking in other people's emotions without even realising, believing they are ours. Either way, we carry memory in our body down to core level, and these subconscious memories vibrate, like programmed microchips in a computer, affecting our behaviour. Discord is clashing, dissonant sound and this is how the turmoil of the mind can feel when we are burdened with the past.  It's time to let go. Visualise yourself as a white lotus, breathe sparkling white prana into the whole body and as you chant I AM, imagine unwanted memories flowing out of you with the sound.  Continue until you feel the 'petals' of your inner self begin to open, glow and radiate. Affirm 'I AM here and now, in this moment.'", "167.mp3", "168.mp3", 45);
	c[45] = new CardSpec("Out of Tune", CardType.WHOLEBODY, "46.png", "When did you last tell yourself you are perfect, just as you are, looking as you do, being yourself, right in this moment? The 'little self' is eternally striving for unachievable perfection, and comparison, judgement and self-criticism all serve to convince us that we are not enough.  If you constantly tell yourself 'I AM NOT', the body begins to manifest this uneasy thought by creating cells which 'are not' in tune: dis-eased.  The truth is, we are perfect right now. Not yesterday, not tomorrow, but precisely in this moment.  So stop searching for confirmation on the outside and make the choice to really support yourself.  Visualise yourself as a white lotus. Breathe sparkling white prana into the whole body and chant I AM. Place your hands where you feel tension or blocked energy and lovingly sound in this powerful affirmation to harmonise yourself.", "169.mp3", "170.mp3", 46);
	c[46] = new CardSpec("Orchestra", CardType.WHOLEBODY, "47.png", "Detailed scientific research has now conclusively proved that emotions affect the cellular structure and workings of our body. Our DNA actually changes shape, according to our feelings.  The lower vibrations (anger, fear, frustration, stress) shorten the DNA strands, whereas the higher ones (gratitude, love, appreciation) cause the DNA to unwind and become longer. We are literally our own orchestra and the melodic harmony of each cell and every organ in our body is governed by our choice of emotions. The positive emotions can boost our immune system and increase our resistance to disease. Stand with your feet firmly placed on the earth. Breathe sparkling white prana into the whole body.  Find a low I AM sound, connect to the earth and chant with gratitude at being given the opportunity to experience this amazing planet.  Become a musician in the universal symphony of life and let your DNA effortlessly unravel.", "171.mp3", "172.mp3", 47);
	c[47] = new CardSpec("Singing Bowl", CardType.WHOLEBODY, "48.png", "Crystal and brass bowls give out an incredibly powerful resonance for healing when vibrated with sound and can be tuned to many different notes with different qualities.  When we are truly connected to Source, there is no duality, no separation, and we can simply experience ourselves as the Singing Bowl through which the oneness of life resonates.  Centre yourself with the in and out-breath and visualise yourself as a white lotus.  Focus your attention just above your crown on a beam of pure white light, like an umbilical cord connecting you to the higher dimensions. Breathe this light down the spine and feel it spread through your body, transforming the lotus into pure crystal. On each in-breath, continue to breathe light into every cell. On each out-breath, sound a high, clear, heavenly I AM. Vibrate your whole crystalline lotus body with sound and sing the pure vibration of life.", "173.mp3", "174.mp3", 48);
	c[48] = new CardSpec("Crescendo", CardType.ANGEL, "49.png", "There are times when we all need to release our feelings, and help is at hand with the Angel of Sound, Crescendo. Whether the problem is frustration, anger, disappointment, hurt, sadness, fear, grief or boredom and depression, using sound is a simple and wonderful way to let it all go. Close your eyes, centre yourself with breathing, and invoke this angel to work with you.  Visualise Crescendo standing behind you. Now bring the problematic situation or person into your mind. Go inside your body and really get in touch with how you feel about it, in every way.  Then begin to make a sound, any sound, to express that feeling. Open your mouth wide, and let this sound grow stronger and stronger into a climax as you allow all old emotion to pour out. When you feel you've released everything, place your hands on your heart and breathe in Crescendo's love and support.", "175.mp3", "176.mp3", 49);
	c[49] = new CardSpec("Dulcimer", CardType.ANGEL, "50.png", "A dulcimer (from the Latin dulce melos - sweet song) was an early stringed instrument with sounding board, and Angel of Sound Dulcimer comes to join you now with the sweet song of compassion - a healing quality we need to give unconditionally to ourselves and others.  Close your eyes, centre yourself with breathing, and invoke this angel to work with you. Visualise Dulcimer standing before you with rays of golden pink light emanating from the heart. Breathe this light into your own heart.  Now bring to mind the person or situation you wish to heal. Begin to make a sweet, gentle sound, sending it from your heart with pure compassion. Each time, breathe in Dulcimer's energy to fill your heart, and emit your sound with loving tenderness.  Continue as long as you wish. Finish by placing your hands on your heart and breathing in Dulcimer's love and support.", "178.mp3", "179.mp3", 50);
	c[50] = new CardSpec("Sanctus", CardType.ANGEL, "51.png", "The Sanctus is traditionally sacred music for religious ritual (from the Latin sanctus  - holy, pure) but Angel of Sound Sanctus comes now to help you consecrate your inner space.  We all need our personal sanctuary where we can retreat in safety to rest, reflect and revive.  Close your eyes, centre yourself with breathing and invoke this angel to work with you.  Visualise Sanctus gently descending into the centre of your body. Breathe in a feeling of deep inner calm. Now begin to make your sound for peace, and visualise a ball of light glowing inside you.  See yourself standing in the centre of that light, guarded by Sanctus.  As you make your sound, feel the light expanding, filling your sacred space with perfect peace.  You are now in your inner sanctuary. Continue as long as you wish, then place your hands on your solar plexus and breathe in Sanctus' loving support.", "181.mp3", "182.mp3", 51);
	c[51] = new CardSpec("Carillon", CardType.ANGEL, "52.png", "Think of an angel. Then think of another angel standing behind, and another, and another, one endless string of angels stretched across eternity, connecting us from now back to the Source. Each angel has a harmonic sound, their ageless melody like the peal of bells or carillon, one note following the next in perfect order.  The Angel of Sound Carillon has come to help you connect to the limitless supply of universal energy.  Close your eyes, centre yourself with breathing and invoke this angel to work with you. Visualise Carillon above you, emanating pink gold light. Find a high pure sound to connect, and as you make the sound, allow pure life force energy to spiral down through your crown, into your body.  Continue as long as you wish.  Finish by placing hands palms upwards on your thighs and receive loving support from Carillon.", "184.mp3", "185.mp3", 52);
	FileHandle handle = Gdx.files.internal("Text/affirmations.txt");
	String list = handle.readString();
	list = list.substring(3);
	String t = "";
	StringTokenizer st = new StringTokenizer(list, "#");
	for(int i = 0; i < 52; i++){
		t= st.nextToken();
		c[i].setCardProperty(CardEnum.AFFIRMATION.getEnumID(), t);
	}
		for(int i = 0; i < 52; i++){
			cards[i] = new Card(c[i]);
		}
	}
	
	public Card[] getCards() {
		return cards;
	}
	
	public Card getCard(int id){
		return cards[id];
	}

	public static AllCards getInstance() {
		return INSTANCE;
	}

	public Card getCurrentCard() {
		return currentCard;
	}
	public void setCurrentCard(int cardid) {
		this.currentCard = cards[cardid-1];
	} 
	
	public Array<Card> setupRevealCards(){
		revealCards = null;
		revealCards = new Array<Card>();
		int x = 0;
		if(SceneHandler.getInstance().getSpread().compareTo(Spread.ANGELS_OF_SOUND) == 0){
			for(int i = 0; i < 8; i++){
				if(i%2 == 0){
					x = MathUtils.random(51);
				}
				else{
					x = MathUtils.random(3)+48;
				}
				if(!revealCards.contains(getCard(x), false)){
					revealCards.add(getCard(x));
				}
				else{
					i--;
				}
			}
		}
		else if(SceneHandler.getInstance().getSpread().compareTo(Spread.MULTI) == 0){
			revealCards.add(getCard(MathUtils.random(5)));
			revealCards.add(getCard(MathUtils.random(5)+6));
			revealCards.add(getCard(MathUtils.random(5)+12));
			revealCards.add(getCard(MathUtils.random(5)+18));
			revealCards.add(getCard(MathUtils.random(5)+24));
			revealCards.add(getCard(MathUtils.random(5)+30));
			revealCards.add(getCard(MathUtils.random(5)+36));
			revealCards.add(getCard(MathUtils.random(5)+42));
			revealCards.add(getCard(MathUtils.random(3)+48));
		}
		else{
		for(int i = 0; i < SceneHandler.getInstance().getSpread().getNumberOfCards(); i++){
			if(SceneHandler.getInstance().getSpread().compareTo(Spread.SYMPHONY_OF_LIFE) == 0){
				if(i == 5){
					x = MathUtils.random(3)+48;
				}
				else{
					x = MathUtils.random(47);
				}
			}
			else{
				x = MathUtils.random(51);
			}
			if(!revealCards.contains(getCard(x), false)){
				revealCards.add(getCard(x));
			}
			else{
				i--;
			}
		}
		}
		return revealCards;
	}
	
	public Array<Card> setupLoadedCards(int[] id){
		loadCards = null;
		loadCards = new Array<Card>();
		for(int i = 0; i < id.length; i++){
			loadCards.add(getCard(id[i]));	
		}
		return loadCards;	
	}
	
	public Array<Card> getRevealCards() {
		return revealCards;
	}

	public Array<Card> getLoadedCards() {	
		return loadCards;
	}

	public void setIndividual(int individual) {
		this.individual = individual;
	}
	
	public Array<Card> getIndividual(){
		inCards = null;
		inCards = new Array<Card>();
		for(int i = individual*6; i < individual*6+6; i++){
			inCards.add(getCard(i));	
		}
		inCards.add(getCard(48));
		inCards.add(getCard(49));
		inCards.add(getCard(50));
		inCards.add(getCard(51));
		return inCards;
	}
	
}
